### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by adelpeuch** [madec-project/ezmaster#3]
Hi,

I'm trying to use EZMaster and i've got an issue with npm install -g ezmaster.
I can post you  /root/npm-debug.log if necessary.

Thanks for your help.

This is the error 

npm WARN peerDependencies The peer dependency castor-clean@* included from ezmaster will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency pm2@* included from ezmaster will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
/root/.nvm/versions/node/v4.1.2/bin/castor-admin -> /root/.nvm/versions/node/v4.1.2/lib/node_modules/ezmaster/bin/admin
/root/.nvm/versions/node/v4.1.2/bin/ezmaster -> /root/.nvm/versions/node/v4.1.2/lib/node_modules/ezmaster/bin/admin

> ezmaster@1.1.3 postinstall /root/.nvm/versions/node/v4.1.2/lib/node_modules/ezmaster
> node ./bin/init

module.js:338
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v4.1.2/lib/node_modules/ezmaster/bin/init'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/root/.nvm/versions/node/v4.1.2/bin/node" "/root/.nvm/versions/node/v4.1.2/bin/npm" "install" "-g" "ezmaster"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! ezmaster@1.1.3 postinstall: `node ./bin/init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ezmaster@1.1.3 postinstall script 'node ./bin/init'.
npm ERR! This is most likely a problem with the ezmaster package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/init
npm ERR! You can get their info via:
npm ERR!     npm owner ls ezmaster
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by parmentf** [comment]
Bad news: using the same versions of node (4.1.2) and npm (2.14.4, which came along with node), I can't reproduce the error.

After 
```bash
$ npm install -g castor-clean
$ npm install -g pm2
```
(with no problems)

I get
```bash
$  npm install -g ezmaster
npm WARN peerDependencies The peer dependency castor-clean@* included from ezmaster will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency pm2@* included from ezmaster will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
/home/parmentf/.nvm/v4.1.2/bin/castor-admin -> /home/parmentf/.nvm/v4.1.2/lib/node_modules/ezmaster/bin/admin
/home/parmentf/.nvm/v4.1.2/bin/ezmaster -> /home/parmentf/.nvm/v4.1.2/lib/node_modules/ezmaster/bin/admin

> ezmaster@1.1.3 postinstall /home/parmentf/.nvm/v4.1.2/lib/node_modules/ezmaster
> node ./bin/init

ezmaster@1.1.3 /home/parmentf/.nvm/v4.1.2/lib/node_modules/ezmaster
├── getport@0.1.0
├── filesize@2.0.4
├── connect-flash@0.1.1
├── async@0.9.2
├── debug@1.0.4 (ms@0.6.2)
├── http-proxy@1.11.2 (eventemitter3@1.1.1, requires-port@0.0.1)
├── ejs@1.0.0
├── sugar@1.4.1
├── mv@2.1.1 (ncp@2.0.0, mkdirp@0.5.1, rimraf@2.4.3)
├── express@3.21.2 (merge-descriptors@1.0.0, escape-html@1.0.2, cookie@0.1.3, commander@2.6.0, cookie-signature@1.0.6, utils-merge@1.0.0, methods@1.1.1, content-type@1.0.1, vary@1.0.1, content-disposition@0.5.0, range-parser@1.0.2, basic-auth@1.0.3, etag@1.7.0, fresh@0.3.0, parseurl@1.3.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, mkdirp@0.5.1, connect@2.30.2)
└── xml2js@0.4.12 (sax@1.1.3, xmlbuilder@3.1.0)
```

It seems that the post-install script cannot execute `/root/.nvm/versions/node/v4.1.2/lib/node_modules/ezmaster/bin/init`, which you can try to run via:
```bash
$ cd /root/.nvm/versions/node/v4.1.2/lib/node_modules/ezmaster
$ node ./bin/init
```

If that command does not yield any error, ezmaster should be installed.
Please, tell us if it works.


Oh. Nothing in common, but I see that the documentation was written at the time where `pm2` was at the 0.10.x version.
Unfortunately, from version 0.12 on (I think), the configuration files had a change in syntax.
So, you should install version 0.10 of pm2 (without any version, I installed pm2@0.15.7):
```bash
$ npm install -g pm2@0.10
```
I will fix the documentation.

**Comment by parmentf** [comment]
Oh. As you work in root directory, maybe it's just rights problem?
I suggest a 
```bash
$ ls -l /root/.nvm/versions/node/v4.1.2/lib/node_modules/ezmaster/bin/init
```

Maybe you need to prefix your npm commands with `sudo`?

**Comment by adelpeuch** [comment]
Thanks for your answer.

I try to change pm2 version and it take me a solution...
In root, i need to use --unsafe-perm parameter on npm command ant it's 
working.

Thanks for your help.

-- 
Alexandre Delpeuch
Responsable du Service Outils Numériques
Direction du Système d'Information
Universite de Limoges
123 Avenue Albert Thomas
87060 Limoges Cedex
tél : 05 55 08 08 10
Num de poste : 38 10
Site web : http://www.unilim.fr/dsi

**Comment by parmentf** [comment]
You're welcome.
Happy to read that it works.

Actually, we don't install as root, so we did not encounter that case.
